add 'images' and 'up' commands to mylx

diff --git a/tests/bin/mylx b/tests/bin/mylx
--- a/tests/bin/mylx
+++ b/tests/bin/mylx
@@ -156,6 +156,23 @@ mylx_list() {
     lxc --project "$LX_PROJECT" list
 }
 
+mylx_images() {
+    mylx_guess "$1" || return 1
+    echo lxc --project "$LX_PROJECT" image list
+    lxc --project "$LX_PROJECT" image list
+}
+
+mylx_up() {
+    if [ -x "./provision.sh" ] ; then
+        echo "Provision"
+        ./provision.sh "$@" || return 1
+    else
+        echo "UP failed: ./provision.sh does not exist or is not executable"
+        return 1
+    fi
+}
+    
+
 mylx_start() {
     mylx_guess "$@" || return 1
     echo lxc --project "$LX_PROJECT" start "$LX_INST"
@@ -200,6 +217,8 @@ usage() {
     echo "     ssh"
     echo "     hostname"
     echo "     list"
+    echo "     images"
+    echo "     up"
     echo "     start"
     echo "     stop"
     echo "     delete|destroy"
